version: '3.8'

services:
    nginx:
        container_name: koopenwin_nginx
        image: nginx:latest
        ports:
            - "${APP_NGINX_PORT}:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - koopenwin_network

    php:
        container_name: koopenwin_web
        build:
            context: .
            dockerfile: Dockerfile
        image: koopenwin:latest
        volumes:
            - ./:/var/www/html
        networks:
            - koopenwin_network

    scheduler:
        container_name: koopenwin_scheduler
        image: koopenwin:latest
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - koopenwin_network
        command: sh -c "while [ true ]; do php /var/www/html/artisan schedule:run --verbose --no-interaction & sleep 60; done"


    queue:
        container_name: koopenwin_queue
        image: koopenwin:latest
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - koopenwin_network
        command: php /var/www/html/artisan queue:work --verbose --tries=3 --timeout=90

networks:
    koopenwin_network:
        driver: bridge
